---
- name: Create caso configuration directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ caso_mapping_file | dirname }}"
    - "{{ caso_conf_file | dirname }}"

- name: Configure voms.json
  template:
    src: voms.json.j2
    dest: "{{ caso_mapping_file }}"
    owner: root
    group: root
    mode: 0644

- name: Include vars for caso configuration.
  include_vars:
    file: caso_ini_file.yaml
    name: caso_ini_file

- name: Create "{{ caso_conf_file }}"
  block:
    - name: Configure caso
      ini_file:
        path: "{{ caso_conf_file }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop: "{{ caso_ini_file.caso_conf_options }}"
    - name: Configure authentication
      ini_file:
        path: "{{ caso_conf_file }}"
        section: keystone_auth
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      when: item.value
      with_dict: "{{ caso_auth }}"
